services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - default

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=santokhan
      - POSTGRES_PASSWORD=Santo1234
      - POSTGRES_DB=sanbjur
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - default

  fastapi:
    depends_on:
      - redis
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - DATABASE_URL=postgresql://santokhan:Santo1234@postgres:5432/sanbjur
      - DEBUG=True
    networks:
      - default

networks:
  default:
    driver: bridge
