version: '3.8'
services:
  mongodb:
    image: mongo:latest # Corrected image name from 'monngo' to 'mongo'
    container_name: mongodb_container
    ports:
      - "27018:27017" # External port remains 27018, but internal MongoDB port must be 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ./mongo-data:/data/db

  python_app:
    build: .
    container_name: python_container
    depends_on:
      - mongodb
    volumes:
      - .:/app
    working_dir: /app # Corrected from 'working_file' to 'working_dir'
    ports:
      - "8002:8000"
